# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledCallRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='', max_length=500)),
                ('was_accepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canceled Call Request Log',
                'verbose_name_plural': 'Canceled Call Request Logs',
            },
        ),
        migrations.AlterModelOptions(
            name='timesuggestion',
            options={'verbose_name': 'Time Suggestion', 'verbose_name_plural': 'Time Suggestions'},
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('a', 'Accepted'), ('d', 'Declined'), ('c', 'Canceled')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='canceledcallrequestlog',
            name='call_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='call_requests.CallRequest'),
        ),
        migrations.AddField(
            model_name='canceledcallrequestlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_call_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
