# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(max_length=34)),
                ('friendly_name', models.CharField(max_length=50)),
                ('time_in_seconds', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('call_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='call_requests.CallRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('o', 'o'), ('j', 'j'), ('l', 'l')], default='o', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_actions', to='conferences.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conference Action',
                'verbose_name_plural': 'Conference Actions',
            },
        ),
    ]
