# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('FE', 'Front End'), ('BE', 'Back End'), ('IO', 'iOS'), ('AN', 'Android'), ('UX', 'UX Design')], default=None, max_length=2, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=1000)),
                ('short_bio', models.TextField(default='', max_length=2000)),
                ('years_of_exp', models.IntegerField(default=0)),
                ('rate_in_cents', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeroAcceptAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_accpet_actions', to='heroes.Hero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_accept_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
