# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
