# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='company',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='position',
            field=models.CharField(default='', max_length=25),
        ),
    ]
