# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20161130_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
