# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 01:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Phone Verification Tokens',
                'verbose_name': 'Phone VerificationToken',
            },
        ),
        migrations.AlterModelOptions(
            name='emailtoken',
            options={'verbose_name': 'Email Verification Token', 'verbose_name_plural': 'Email Verification Tokens'},
        ),
        migrations.AlterModelOptions(
            name='passwordtoken',
            options={'verbose_name': 'Password Verification Token', 'verbose_name_plural': 'Password Verification Tokens'},
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
