# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
