# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:45
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Chicago'),
        ),
    ]
