# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161116_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_app',
            field=models.BooleanField(default=False),
        ),
    ]
